# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: "--as-cran --no-build-vignettes --no-manual"
r_build_args: "--no-manual"

# because of INLA on Travis:
# `/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found`
env:
  global:
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal1-dev
      - gdal-bin
      - libproj-dev
      - proj-data
      - proj-bin
      - libgeos-dev

# before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
# deploy:
#   provider: script
#   script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
#   skip_cleanup: true

r_github_packages:
  - r-lib/covr

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
  # - Rscript -e "install.packages('INLA', repos = c(getOption('repos'), INLA = 'https://inla.r-inla-download.org/R/stable'), dep = TRUE)"

# after_success:
#   - Rscript -e 'covr::codecov()'
